use anyhow::Result;
use async_trait::async_trait;

use crate::models::{AlgorithmDecision, AnalysisResult, SocialPost};

/// Pluggable algorithm contract.
///
/// Each algorithm receives the full set of collected posts and an already
/// partially-populated `AnalysisResult` (e.g. containing sentiment scores
/// computed by an earlier algorithm), and appends its own `AlgorithmDecision`
/// to `result.decisions`.
///
/// Algorithms are intentionally stateless so they can be loaded dynamically
/// or generated by LLMs.
#[async_trait]
pub trait Algorithm: Send + Sync {
    /// Short, machine-readable name (e.g. "sentiment", "trend-detection")
    fn name(&self) -> &str;

    /// Run the algorithm and return any decisions.
    ///
    /// Algorithms SHOULD NOT mutate `result.sentiments` or `result.trends` –
    /// those are populated by dedicated algorithms. They MAY read them.
    async fn run(
        &self,
        posts: &[SocialPost],
        result: &AnalysisResult,
    ) -> Result<Vec<AlgorithmDecision>>;
}

pub mod sentiment;
pub mod trend;

pub use sentiment::SentimentAlgorithm;
pub use trend::TrendAlgorithm;
